[build]
builder = "dockerfile"
dockerfilePath = "railway.dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Cron jobs configuration
[[services]]
name = "validator-check-cron"
type = "cron"
schedule = "0 */2 * * *"  # Every 2 hours
command = "curl -X POST https://delicious-babies-production.up.railway.app/trigger-validator-check -H 'Content-Type: application/json' -d '{}'"

[[services]]
name = "batch-sync-cron"  
type = "cron"
schedule = "0 */6 * * *"  # Every 6 hours
command = "curl -X POST https://delicious-babies-production.up.railway.app/trigger-batch-sync -H 'Content-Type: application/json' -d '{}'" 